"""lang added

Revision ID: 98ebe84acfdc
Revises: 603193883638
Create Date: 2025-06-17 15:20:31.173942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ebe84acfdc'
down_revision: Union[str, None] = '603193883638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.String(length=2), server_default='uz', nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###
